# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0f\x63lau_doom.agent\"\xe7\x01\n\tGameState\x12\x0e\n\x06health\x18\x01 \x01(\x05\x12\x0c\n\x04\x61mmo\x18\x02 \x01(\x05\x12\r\n\x05kills\x18\x03 \x01(\x05\x12\x17\n\x0f\x65nemies_visible\x18\x04 \x01(\x05\x12\x12\n\nposition_x\x18\x05 \x01(\x02\x12\x12\n\nposition_y\x18\x06 \x01(\x02\x12\x12\n\nposition_z\x18\x07 \x01(\x02\x12\r\n\x05\x61ngle\x18\x08 \x01(\x02\x12\x14\n\x0c\x65pisode_time\x18\t \x01(\x02\x12\x0f\n\x07is_dead\x18\n \x01(\x08\x12\x0c\n\x04tick\x18\x0b \x01(\r\x12\x14\n\x0c\x63\x61scade_mode\x18\x0c \x01(\t\"\x90\x01\n\x06\x41\x63tion\x12\x30\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\x1b.clau_doom.agent.ActionType\x12\x16\n\x0e\x64\x65\x63ision_level\x18\x02 \x01(\x05\x12\x12\n\nlatency_ms\x18\x03 \x01(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x14\n\x0crule_matched\x18\x05 \x01(\t*\xa1\x01\n\nActionType\x12\x1b\n\x17\x41\x43TION_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tMOVE_LEFT\x10\x01\x12\x0e\n\nMOVE_RIGHT\x10\x02\x12\x10\n\x0cMOVE_FORWARD\x10\x03\x12\x11\n\rMOVE_BACKWARD\x10\x04\x12\r\n\tTURN_LEFT\x10\x05\x12\x0e\n\nTURN_RIGHT\x10\x06\x12\n\n\x06\x41TTACK\x10\x07\x12\x07\n\x03USE\x10\x08\x32\x92\x01\n\x0c\x41gentService\x12;\n\x04Tick\x12\x1a.clau_doom.agent.GameState\x1a\x17.clau_doom.agent.Action\x12\x45\n\nStreamTick\x12\x1a.clau_doom.agent.GameState\x1a\x17.clau_doom.agent.Action(\x01\x30\x01\x42+Z)github.com/sangyi/clau-doom/proto/agentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/sangyi/clau-doom/proto/agentpb'
  _globals['_ACTIONTYPE']._serialized_start=414
  _globals['_ACTIONTYPE']._serialized_end=575
  _globals['_GAMESTATE']._serialized_start=33
  _globals['_GAMESTATE']._serialized_end=264
  _globals['_ACTION']._serialized_start=267
  _globals['_ACTION']._serialized_end=411
  _globals['_AGENTSERVICE']._serialized_start=578
  _globals['_AGENTSERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
